before_script:
    - git submodule update --init
    
ubuntuBuild:
    image: eschiller/libalazar-builder
    script: 
        - mkdir build
        - cd build
        - cmake -DSIM=true ../
        - sh ../src/lib/version.sh > ../src/lib/version.h
        - make clean install
        - export LD_LIBRARY_PATH=./bin
        - cd ../src/python 
        - which python
        - python apiTest.py 
        - cd ../../build
    #artifacts:
    #    - bin/*.so

    tags:
        - ubuntu
        
windowsAPITest:    

    script:
        - mkdir build
        - cd build
        - cmake -G "MSYS Makefiles" -DSIM=true ../
        - sh ../src/lib/version.sh > ../src/lib/version.h
        - make clean install
        - cd ../src/python 
        - which python
        - python apiTest.py 
        - cd ../../build
    tags:
        - windows
    
windowsDLLBuild:    

    script:
        - mkdir build
        - cd build
        - cmake -G "MSYS Makefiles" -DLOG_LEVEL=2 ../
        - sh ../src/lib/version.sh > ../src/lib/version.h
        - make clean install
    tags:
        - windows
    artifacts:
        paths:
            - build/dist
    only:
        - tags    
