before_script:
    - git submodule update --init

ubuntuBuild:
    image: eschiller/libalazar-builder:v2
    script:
        - mkdir build
        - cd build
        - cmake -DSIM=true ../
        - make clean install
        - export LD_LIBRARY_PATH=./bin
        - cd ../src/python
        - which python
        - python -m unittest
        - cd ../../build
    #artifacts:
    #    - bin/*.so

    tags:
        - ubuntu

windowsAPITest:

    script:
        - mkdir build
        - cd build
        - cmake -G "MSYS Makefiles" -DSIM=true ../
        - make clean install
        - cd ../src/python
        - which python
        - python -m unittest
        - cd ../../build
    tags:
        - windows

windowsDLLBuild:

    script:
        - mkdir build
        - cd build
        - cmake -G "MSYS Makefiles" -DLOG_LEVEL=2 ../
        - make clean install
    tags:
        - windows
    artifacts:
        paths:
            - build/dist
    only:
        - tags
